Update animationHelpers.js
tech-extremists/appTestRepo pull request #3
Opened 2024-12-19 15:56 UTC by tech-extremists

2025-01-03 13:58 UTC, ali-tunahan requested changes
!cond_accept

2025-01-03 13:58 UTC, ali-tunahan commented on animationHelpers.js
> +        vertexArray = getFrameData();
nuh uh 
```suggestion
        vertexArray = getFrameData("cu");
```

2025-01-03 14:01 UTC, ali-tunahan commented on animationHelpers.js
>          keyframes.translationVals.push([xTransVal, yTransVal, 0.0]);
!cond_accept

2025-01-03 14:01 UTC, ali-tunahan reviewed
!cond_accept

2025-01-16 22:37 UTC, tech-extremists commented on animationHelpers.js
> +        vertexArray
!suggest remove this line.

2025-01-16 22:38 UTC, tech-extremists commented on animationHelpers.js
> +        vertexArray
!suggest remove this line.

2025-01-16 22:40 UTC, tech-extremists commented on animationHelpers.js
> +        keyframes.translationVals.add(vertexArray);
!suggest add comments

2025-01-16 22:43 UTC, tech-extremists commented on animationHelpers.js
> +vertexArray = [];
!suggest Fill this array with 2,3 and 5

2025-01-16 22:45 UTC, tech-extremists commented on animationHelpers.js
> +        vertexArray = getFrameData();
!suggest wrap getFrameData() inside getVertices() only for this line.

2025-01-16 22:54 UTC, tech-extremists commented on animationHelpers.js
> +vertexArray = [];
!suggest initialize this array with 2,3 and 5

2025-01-16 22:56 UTC, tech-extremists commented on animationHelpers.js
> +vertexArray = [];
!suggest initialize this array with 2,3 and 5

2025-01-16 22:57 UTC, tech-extremists commented on animationHelpers.js
> +vertexArray = [];
!suggest initialize this array with 2,3 and 5

2025-01-16 22:58 UTC, tech-extremists commented on animationHelpers.js
> +vertexArray = [];
!suggest initialize this array with 2,3 and 5

2025-02-11 14:07 UTC, tech-extremists commented on animationHelpers.js
> +        vertexArray = getFrameData();
!suggest add comments

2025-02-11 14:08 UTC, closed without merging